import pytest
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

from aily.learning.loop import LearningLoop


@pytest.fixture
def mock_queue_db():
    db = MagicMock()
    db.get_note_snapshot = AsyncMock()
    return db


@pytest.fixture
def mock_graph_db():
    db = MagicMock()
    db.insert_node = AsyncMock()
    db.insert_edge = AsyncMock()
    db.insert_preference = AsyncMock()
    return db


@pytest.fixture
def mock_llm():
    llm = MagicMock()
    llm.chat_json = AsyncMock(return_value={
        "new_entities": [{"label": "AI", "type": "topic"}],
        "corrected_entities": [],
        "new_edges": [{"source_label": "AI", "target_label": "ML", "relation_type": "related"}],
        "inferred_preferences": ["user likes technical content"],
    })
    return llm


@pytest.fixture
def tmp_vault_path(tmp_path):
    return tmp_path / "vault"


@pytest.fixture
async def learning_loop(tmp_vault_path, mock_queue_db, mock_graph_db, mock_llm):
    tmp_vault_path.mkdir()
    loop = LearningLoop(
        vault_path=tmp_vault_path,
        queue_db=mock_queue_db,
        graph_db=mock_graph_db,
        llm=mock_llm,
        debounce_seconds=0.1,
    )
    return loop


@pytest.mark.asyncio
async def test_is_aily_generated_true():
    content = "---\naily_generated: true\n---\n\nSome content"
    assert LearningLoop._is_aily_generated(content) is True


@pytest.mark.asyncio
async def test_is_aily_generated_false():
    content = "---\ntitle: My Note\n---\n\nSome content"
    assert LearningLoop._is_aily_generated(content) is False


@pytest.mark.asyncio
async def test_is_aily_generated_no_frontmatter():
    content = "# My Note\n\nSome content"
    assert LearningLoop._is_aily_generated(content) is False


@pytest.mark.asyncio
async def test_persist_insights(learning_loop, mock_graph_db):
    result = {
        "new_entities": [{"label": "AI", "type": "topic"}],
        "corrected_entities": [],
        "new_edges": [{"source_label": "AI", "target_label": "ML", "relation_type": "related"}],
        "inferred_preferences": ["user likes technical content"],
    }
    await learning_loop._persist_insights(result, "test_note.md")

    mock_graph_db.insert_node.assert_called_once()
    args = mock_graph_db.insert_node.call_args[0]
    assert args[1] == "topic"
    assert args[2] == "AI"
    assert "learning_loop:test_note.md" in args[3]

    mock_graph_db.insert_edge.assert_called_once()
    mock_graph_db.insert_preference.assert_called_once()


@pytest.mark.asyncio
async def test_persist_insights_empty_result(learning_loop, mock_graph_db):
    result = {
        "new_entities": [],
        "corrected_entities": [],
        "new_edges": [],
        "inferred_preferences": [],
    }
    await learning_loop._persist_insights(result, "test_note.md")

    mock_graph_db.insert_node.assert_not_called()
    mock_graph_db.insert_edge.assert_not_called()
    mock_graph_db.insert_preference.assert_not_called()


@pytest.mark.asyncio
async def test_process_file_skips_non_aily_generated(learning_loop, tmp_vault_path, mock_queue_db):
    note_path = tmp_vault_path / "user_note.md"
    note_path.write_text("# User Note\n\nNot generated by Aily.")
    mock_queue_db.get_note_snapshot.return_value = {"original_markdown": "original"}

    await learning_loop._process_file(Path("user_note.md"))

    mock_queue_db.get_note_snapshot.assert_not_called()


@pytest.mark.asyncio
async def test_process_file_no_snapshot(learning_loop, tmp_vault_path, mock_queue_db, mock_llm):
    note_path = tmp_vault_path / "aily_note.md"
    note_path.write_text("---\naily_generated: true\n---\n\nContent")
    mock_queue_db.get_note_snapshot.return_value = None

    await learning_loop._process_file(Path("aily_note.md"))

    mock_llm.chat_json.assert_not_called()


@pytest.mark.asyncio
async def test_process_file_full_flow(learning_loop, tmp_vault_path, mock_queue_db, mock_llm, mock_graph_db):
    note_path = tmp_vault_path / "aily_note.md"
    note_path.write_text("---\naily_generated: true\n---\n\nUpdated content")
    mock_queue_db.get_note_snapshot.return_value = {"original_markdown": "Original content"}
    mock_llm.chat_json.return_value = {
        "new_entities": [{"label": "AI", "type": "topic"}],
        "corrected_entities": [],
        "new_edges": [],
        "inferred_preferences": ["likes AI"],
    }

    await learning_loop._process_file(Path("aily_note.md"))

    mock_queue_db.get_note_snapshot.assert_called_once_with("aily_note.md")
    mock_llm.chat_json.assert_called_once()
    mock_graph_db.insert_node.assert_called_once()
    mock_graph_db.insert_preference.assert_called_once()


@pytest.mark.asyncio
async def test_start_stop(learning_loop):
    await learning_loop.start()
    assert learning_loop._task is not None
    assert not learning_loop._stop_event.is_set()

    await learning_loop.stop()
    assert learning_loop._stop_event.is_set()
    assert learning_loop._task is None or learning_loop._task.done()
