"""Data models for Aily Three-Mind System.

Follows the same patterns as aily/thinking/models.py for consistency.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum, auto
from typing import Any


class ProposalType(Enum):
    """Type of proposal generated by a mind."""

    INNOVATION = auto()  # TRIZ-based insight
    BUSINESS = auto()  # GStack-based evaluation
    SYNTHESIS = auto()  # Cross-framework synthesis


class ProposalStatus(Enum):
    """Status of a proposal in its lifecycle."""

    PENDING = auto()  # Generated but not yet delivered
    PROPOSED = auto()  # Proposed by a thinking framework
    DELIVERED = auto()  # Sent to Feishu/Obsidian
    ARCHIVED = auto()  # Moved to archive after 30 days
    REJECTED = auto()  # Below quality threshold


class ProposalStage(Enum):
    """Venture-funnel stage for a proposal."""

    PENDING_INNOVATION = auto()  # Waiting for Reactor scoring
    PENDING_BUSINESS = auto()    # Passed innovation, waiting for GStack
    INCUBATING = auto()          # Approved by GStack (build_it)
    REJECTED_INNOVATION = auto()  # Failed innovation screening
    REJECTED_BUSINESS = auto()    # Failed GStack validation


@dataclass
class Proposal:
    """A single proposal generated by an Aily mind.

    Proposals are actionable insights or recommendations generated
    from knowledge analysis. They follow the DIKIWI pipeline's
    Impact stage (I in DIKIWI).
    """

    # Identity
    id: str = field(default_factory=lambda: f"proposal_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{__import__('random').randint(0, 9999):04d}")
    mind_name: str = ""  # "innovation" or "entrepreneur"
    proposal_type: ProposalType = ProposalType.INNOVATION

    # Content
    title: str = ""
    content: str = ""
    summary: str = ""  # One-line summary for Feishu notifications

    # Quality metrics
    confidence: float = 0.0  # 0.0-1.0, must be >= 0.7 for delivery
    priority: str = "medium"  # "critical", "high", "medium", "low"

    # Venture-funnel scores
    innovation_score: float = 0.0
    business_score: float = 0.0
    rejection_reason: str = ""
    validation_attempts: int = 0
    stage: ProposalStage = ProposalStage.PENDING_INNOVATION

    # Source tracking (links back to knowledge)
    source_knowledge_ids: list[str] = field(default_factory=list)  # Node IDs that informed this proposal
    source_session_id: str = ""  # Session that generated this
    framework_used: str = ""  # "TRIZ", "GStack", "McKinsey", etc.

    # Lifecycle
    status: ProposalStatus = ProposalStatus.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    delivered_at: datetime | None = None
    archived_at: datetime | None = None

    # Delivery tracking
    feishu_message_id: str | None = None
    obsidian_note_path: str | None = None

    # User feedback (for quality improvement)
    user_rating: int | None = None  # 1-5 stars
    user_feedback: str | None = None

    # Additional metadata
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate proposal after creation."""
        # Ensure confidence is in valid range
        self.confidence = max(0.0, min(1.0, self.confidence))

        # Auto-reject if below quality threshold
        if self.confidence < 0.7 and self.status == ProposalStatus.PENDING:
            self.status = ProposalStatus.REJECTED

    def to_markdown(self) -> str:
        """Convert proposal to Markdown for Obsidian."""
        def _as_markdown(value: Any) -> str:
            if isinstance(value, str):
                return value
            if isinstance(value, (int, float, bool)) or value is None:
                return str(value)
            return json.dumps(value, ensure_ascii=False, indent=2)

        lines = [
            f"# {self.title}",
            "",
            f"**Type:** {self.proposal_type.name}",
            f"**Confidence:** {self.confidence:.0%}",
            f"**Priority:** {self.priority}",
            f"**Framework:** {self.framework_used}",
            f"**Generated:** {self.created_at.strftime('%Y-%m-%d %H:%M')}",
            f"**Mind:** {self.mind_name}",
            "",
            "## Summary",
            "",
            _as_markdown(self.summary),
            "",
            "## Details",
            "",
            _as_markdown(self.content),
            "",
        ]

        if self.source_knowledge_ids:
            lines.extend([
                "## Source Knowledge",
                "",
            ])
            for node_id in self.source_knowledge_ids[:10]:  # Limit to first 10
                lines.append(f"- [[{node_id}]]")
            lines.append("")

        if self.metadata:
            lines.extend([
                "## Metadata",
                "",
                "```yaml",
            ])
            for key, value in self.metadata.items():
                lines.append(f"{key}: {_as_markdown(value)}")
            lines.extend([
                "```",
                "",
            ])

        return "\n".join(lines)

    def to_feishu_summary(self) -> str:
        """Convert to brief summary for Feishu notification."""
        emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(
            self.priority, "⚪"
        )
        return f"{emoji} **{self.title}**\n{self.summary}\n_Confidence: {self.confidence:.0%}_"


@dataclass
class DikiwiStageMetrics:
    """Metrics for a single DIKIWI stage."""

    stage_name: str  # "Data", "Information", "Knowledge", "Insight", "Wisdom", "Impact"
    items_processed: int = 0
    items_promoted: int = 0
    average_processing_time_ms: float = 0.0
    errors: int = 0


@dataclass
class DikiwiPipelineMetrics:
    """Metrics for the full DIKIWI pipeline."""

    input_id: str  # Source input (RainDrop ID, etc.)
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: datetime | None = None
    stage_metrics: list[DikiwiStageMetrics] = field(default_factory=list)

    @property
    def total_time_ms(self) -> float:
        """Calculate total pipeline time."""
        if not self.completed_at:
            return 0.0
        return (self.completed_at - self.started_at).total_seconds() * 1000


@dataclass
class SessionState:
    """State tracking for a mind session (for replay/debugging)."""

    session_id: str
    mind_name: str
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    events: list[dict[str, Any]] = field(default_factory=list)

    def log_event(self, event_type: str, data: dict[str, Any]) -> None:
        """Log an event for session replay."""
        self.events.append({
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "type": event_type,
            "data": data,
        })

    def to_replay_log(self) -> dict[str, Any]:
        """Export session as replay log for debugging."""
        return {
            "session_id": self.session_id,
            "mind_name": self.mind_name,
            "started_at": self.started_at.isoformat(),
            "event_count": len(self.events),
            "events": self.events,
        }
